---

- hosts: localhost
  gather_facts: no
  vars:
    test: true
    gcp_region: us-east1
    gcp_zone: us-east1-b
    gcp_project: ea-movieverse
    gcp_cred_kind: serviceaccount
    gcp_cred_file: credentials.json
    source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20190617 
  roles:
    - role: gcp-network

    - role: gcp-instance
      vars:
        gcp_machine_type: n1-standard-2
        instances:
          - { index: 1, tag: movieverse }
        disk_size: 50
        disk_type: pd-standard
        type: movieverse
        external_ip: true

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for instances to respond
      wait_for:
        host: "{{ item }}"
        port: 22
      loop: "{{ groups['all'] }}"

- hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: movieverse-content
      vars:
        tar_name: movieverse-deployment.tar.gz

    - role: python

    - role: docker

    - role: postgres

    - role: app
