version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  nginx:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - avatars:/usr/share/nginx/html/static/avatars
  movieverse1:
    image: movieverse
    container_name: movieverse1
    expose:
      - 8080
    volumes:
      - avatars:/avatars
  movieverse2:
    image: movieverse
    container_name: movieverse2
    expose:
      - 8080
    volumes:
      - avatars:/avatars
volumes:
  avatars: